### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by vinaygaba** [forestryio/hugo-theme-novela#56]
I've tried a bunch of stuff that I read in different forums but none seem to work for me. I've included this in my config.yaml file

```yml
PygmentsCodeFencesGuessSyntax: true
PygmentsCodeFences: true
pygmentsUseClasses: true
```

This is what the code in the blog looks like when I try to either use backticks with language or make use of hugu's highlight block. 

<img width="779" alt="Screen Shot 2020-09-27 at 9 35 15 PM" src="https://user-images.githubusercontent.com/4281910/94391051-58bc4900-0109-11eb-9abc-33fbee73d161.png">
